### ISSUE TITLE
Invalid Timezone error

### ISSUE THREAD

**Issue by SergeyMell** [panthomakos/timezone#75]
Recently I started to get Timezone::Error::InvalidZone very often for valid coordinates. After retrying the request (sometime it required several repeats) it starts working ok

**Comment by panthomakos** [comment]
@SergeyMell you may be hitting an API request limit for Google of Geonames depending on your usage. If you believe the issue is due to the `timezone` gem, please provide me with some more detailed information so I can help debug! I would recommend checking your usage in Google/Geonames to see if you were hitting an API limit first.

**Comment by SergeyMell** [comment]
I used Geonames service. Despite it says it has 2000 requests per hour limit, I failed to reach it event making 5000 requests in a loop one by one... Any case I can't reproduce the issue for now so I think it was caused by some internal service problems.
