### ISSUE TITLE
Is it possible to add additional params for geonames?

### ISSUE THREAD

**Issue by dobryakov** [panthomakos/timezone#78]
http://www.geonames.org/export/web-services.html#timezone
Parameters : lat,lng, radius (buffer in km for closest timezone in coastal areas),lang (for countryName), date (date for sunrise/sunset);

Is it possible to add these params when calling .lookup?

**Comment by panthomakos** [comment]
Adding `radius` seems possible. Can you outline an example use-case for how you envision that value would be configured?

I don't see how the other options would be useful because the `lookup` call is only interested in the timezone name. Can you provide some more details about how these other parameters would be used; or how they would alter the lookup result?

**Comment by panthomakos** [comment]
FYI: this PR was opened, but never completed, and it adds the `radius` option: https://github.com/panthomakos/timezone/pull/55
