### ISSUE TITLE
Stub Timezone for Rspec

### ISSUE THREAD

**Issue by Shuiei** [panthomakos/timezone#96]
Hello,

I have found your gem really useful but I have an issue with it. It seems that I can't stub the HTTP calls made to google maps API from your gem.

I tried to put inside my `rspec/support` a file named `timezone.rb` and put inside `::Timezone::Lookup.config(:test)`. It seems the call is still made since WebMock raise me an error saying that no HTTP call is allowed.

Do you have any way to do it? Since I was not able to find any solution by reading your source code.

Thanks =D

**Comment by panthomakos** [comment]
Can you please provide the version of the gem that you are using; and a minimal reproducible example?

Are you sure the support file is being loaded and not overwritten by another timezone configuration block?

When you configure the test adapter this way, there is no possibility for a call to still be made to Google because the underlying adapter changes to an in memory implementation.

**Comment by Shuiei** [comment]
Ya have found the way to solve my problem. You was right I didn'nt set correctly the test configuration. I close this issue.
Thanks for your help 👍

**Comment by panthomakos** [comment]
Glad you've worked it out!

**Comment by vkowencn** [comment]
> Ya have found the way to solve my problem. You was right I didn'nt set correctly the test configuration. I close this issue. Thanks for your help 👍

Can you please explain how you got this issue resolved I am facing exactly the same issue ? Thanks in Advance.
